action_id: trunk-upgrade-available
date: 2024-12-06 19:20:02
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 0
  out: "notifications_to_delete:\n  - trunk-check-upgrade\n  - trunk-upgrade\n"
  err: ""
timestamp: 1733512802
full_timestamp:
  nanos: 729394000
  seconds: 1733512802
trunk_version: 1.22.8
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
