action_id: trunk-upgrade-available
date: 2024-12-06 19:20:57
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: .trunk/trunk.yaml
result:
  exit_code: 0
  out: "notifications_to_delete:\n  - trunk-check-upgrade\n  - trunk-upgrade\n"
  err: ""
timestamp: 1733512857
full_timestamp:
  nanos: 589851000
  seconds: 1733512857
trunk_version: 1.22.8
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
