action_id: trunk-upgrade-available
date: 2024-12-06 19:28:18
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: .trunk/trunk.yaml
result:
  exit_code: 0
  out: "notifications_to_delete:\n  - trunk-check-upgrade\n  - trunk-upgrade\n"
  err: ""
timestamp: 1733513298
full_timestamp:
  nanos: 306329000
  seconds: 1733513298
trunk_version: 1.22.8
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
