action_id: trunk-whoami
date: 2024-12-06 19:28:13
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Not logged in. Run \"trunk login\" to login\x1b[0m\n"
  err: ""
timestamp: 1733513293
full_timestamp:
  nanos: 527863000
  seconds: 1733513293
trunk_version: 1.22.8
