action_id: trunk-cache-prune
date: 2024-12-06 18:19:31
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1733509171
full_timestamp:
  nanos: 1625000
  seconds: 1733509171
trunk_version: 1.22.8
